name: we_care
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  supabase_flutter: ^2.8.4
  flutter_native_splash: ^2.4.6
  dio: ^5.8.0+1
  flutter_stripe: ^11.5.0
  dartz: ^0.10.1
  google_maps_flutter: ^2.12.2
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets\fonts\Rubik-Italic-VariableFont_wght.ttf
