// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiI9CW0YjwH1_sNqYLhS7_30sDFhIdm_Y',
    appId: '1:186024646518:web:a50bb044a0cbda304a0c57',
    messagingSenderId: '186024646518',
    projectId: 'wecare-a1a3a',
    authDomain: 'wecare-a1a3a.firebaseapp.com',
    storageBucket: 'wecare-a1a3a.firebasestorage.app',
    measurementId: 'G-D7JPJD53B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoEW7Xku_B_us_6qOnDADVdVdEQ5ahFZY',
    appId: '1:186024646518:android:d689323359b3026e4a0c57',
    messagingSenderId: '186024646518',
    projectId: 'wecare-a1a3a',
    storageBucket: 'wecare-a1a3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL_TVtwlALO5sCp8u9ZAh-EjSIurKVnFQ',
    appId: '1:186024646518:ios:fa2914a76c45e1f04a0c57',
    messagingSenderId: '186024646518',
    projectId: 'wecare-a1a3a',
    storageBucket: 'wecare-a1a3a.firebasestorage.app',
    iosBundleId: 'com.example.weCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL_TVtwlALO5sCp8u9ZAh-EjSIurKVnFQ',
    appId: '1:186024646518:ios:fa2914a76c45e1f04a0c57',
    messagingSenderId: '186024646518',
    projectId: 'wecare-a1a3a',
    storageBucket: 'wecare-a1a3a.firebasestorage.app',
    iosBundleId: 'com.example.weCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiI9CW0YjwH1_sNqYLhS7_30sDFhIdm_Y',
    appId: '1:186024646518:web:671f0090920f9f5f4a0c57',
    messagingSenderId: '186024646518',
    projectId: 'wecare-a1a3a',
    authDomain: 'wecare-a1a3a.firebaseapp.com',
    storageBucket: 'wecare-a1a3a.firebasestorage.app',
    measurementId: 'G-M6DKW4N7ZY',
  );
}
